### ISSUE TITLE
Taking over sinatra-logger

### ISSUE THREAD

**Issue by kematzy** [minodes/sinatra-logger#1]
Hi,

I just saw your gem in Ruby Weekly email newsletter.

Can we work out some way for you guys to take over the 'sinatra-logger' gem (namespace)? 

I'm no longer using Sinatra, so it would be great for everyone if that could be done.

Please let me know.

**Comment by devyhia** [comment]
Hey,

Thank you for contacting us!

We would love to take over the `sinatra-logger` namespace. Can you remove
the `sinatra-logger` gem from RubyGems.org?

-- 
Yehya Abouelnaga
Software Engineering Intern


*Minodes GmbH*
Friedrichstraße 224 | 10969 Berlin
Email: firstname.lastname@minodes.com <johanna.weber@minodes.com>
Web: www.minodes.com
Blog: www.minodes.com/blog  <http://www.minodes.com/blog>
Phone: +49 30 208 473 870 (Assistance)

Follow us on Twitter: @Minodes <https://twitter.com/minodes>
Like us on facebook: www.facebook.com/minodes

Managing Directors / Geschäftsführer: Tim Wegner, Alexander Köth
Amtsgericht Charlottenburg | HRB 152389 B
USt.IdNr.: DE290944129
Confidentiality Notice: This message (including any attachments) is
confidential and may be privileged. It may be read, copied and used only by
the intended recipient. If you have received it in error please contact the
sender (by return e-mail) immediately and delete this message. Any
unauthorized use or dissemination of this message in whole or in parts is
strictly prohibited.

**Comment by kematzy** [comment]
Hi, 

Can you please confirm the email address on your RubyGems account that should take over?

I will add it as an owner and you can then take over from 1.x scope, leaving my old gems in place just incase someone is depending upon them for some legacy app.

**Comment by devyhia** [comment]
@kematzy Thank you! The email address is `yehya.abouelnaga@minodes.com`.

**Comment by devyhia** [comment]
@kematzy Thank you! I will publish a new version soon :)
