### ISSUE TITLE
Documentation needed: How to log from another ruby file?

### ISSUE THREAD

**Issue by patchin** [minodes/sinatra-logger#4]
I've set up the logger in my Sinatra application. I can log from methods defined in the same class where I set up the logger. How to I log from another method in another ruby file that gets called by my Sinatra application? I get a NameError when I try logger.info "foo". Am I missing some ruby convention of using loggers? Thanks

**Comment by devyhia** [comment]
@patchin Hey, I just saw your issue. Did you find a way around that?

**Comment by patchin** [comment]
Hi @devyhia,
Yes, the details are fuzzy right now but I did the following in my Sinatra app:
===
require 'sinatra/logger'
...
# Passenger provides the :starting_worker_process event for executing
# code after it has forked, so we use that and reconnect immediately.
# Fixes syslog problem when running as a service.
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    ::SemanticLogger.reopen if forked
  end
end
...
# example of using logging in a module
module QueryTimerInstrumentation
  module_function
  include SemanticLogger::Loggable

  def before_query(query)
    logger.info "Query: \"#{query.query_string.gsub("\n", "")}\""
  end

  def after_query(query)
    # Even though this doesn't do anything, we must leave this defined or else.
  end
end
...
class App1 < Sinatra::Base
  include SemanticLogger::Loggable

  configure :production, :development do
    logger = SemanticLogger['App1']
    # Instead of using Rack::CommonLogger we use Clogger which also logs browser info.
    use Clogger, format: Clogger::Format::Combined, logger: logger
  end
  ...
end
===
In a different class that gets used by my Sinatra app I
put the include statement:
===
require 'sinatra/base'
require 'sinatra/logger'

class Foo
  include SemanticLogger::Loggable
  ...
  def bar
    logger.info "blah"
  end
end
===

**Comment by devyhia** [comment]
@patchin Alright, great to know :) I will try to reproduce the issue and, then, add your snippet to the documentation. Thank you.

**Comment by patchin** [comment]
Thanks!

**Comment by jonydev** [comment]
Hi, I met the same problem, but when I include SemanticLogger, alert that can't find the class. Is it your custom class?

**Comment by devyhia** [comment]
@jonydev Hey, you need to require `require 'sinatra/logger'` (`logger` instead of `log`).

**Comment by jonydev** [comment]
@devyhia I have require 'sinatra/logger', but can't find the class.
 I'm using the logger between some middleware, in the subclass of Sinatra::Base, the logger can be found, but in other class, it would not be found.

**Comment by devyhia** [comment]
@jonydev Could you please provide an example/gist/code to reproduce the issue?
