### ISSUE TITLE
Documentation on "require"

### ISSUE THREAD

**Issue by rabidscorpio** [minodes/sinatra-logger#6]
@devyhia Before you do another release, can you add a note to the readme on the usage saying that you need to ```require 'sinatra/logger```, not "sinatra-logger". It took me a little bit of time to figure that one out because I couldn't figure out why the app couldn't see the gem.

Also, a release would be nice so that I can add the gem instead of having bundler pull from github. Cheers!

**Comment by devyhia** [comment]
Okay, I will add that and make a release.

**Comment by devyhia** [comment]
@rabidscorpio A new version is pushed, and the documentation is added. If you come through any bug, or have an improvement/suggestion, please, let us know!
https://rubygems.org/gems/sinatra-logger/versions/0.3.2
